version: '3'
services:
  nginx_destination_distributer:
    image: nginx
    container_name: dest_dist
    volumes:
      - $PWD/dest_dist/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/dest_dist/access.log:/var/log/nginx/access.log
    network_mode: host
      #    restart: unless-stopped
  nginx_source_distributer:
    image: nginx
    container_name: sourc_dist
    volumes:
      - $PWD/sourc_dist/nginx.conf:/etc/nginx/nginx.conf
      - $PWD/sourc_dist/access.log:/var/log/nginx/access.log
    network_mode: host
      #    restart: unless-stopped

